// Generated by CoffeeScript 1.10.0
(function() {
  var coffee, gulp, lazypipe, plumber, srcWatch, watch;

  gulp = require('gulp');

  coffee = require('gulp-coffee');

  plumber = require('gulp-plumber');

  watch = require('gulp-watch');

  lazypipe = require('lazypipe');

  srcWatch = function(glob) {
    return gulp.src(glob).pipe(watch(glob)).pipe(plumber());
  };

  gulp.task('default', function() {
    srcWatch('src/*/*.coffee').pipe(coffee()).pipe(gulp.dest('generators/'));
    return srcWatch('src/*/templates/**/*.*').pipe(gulp.dest('generators/'));
  });

}).call(this);
